services:
  mongo:
    image: mongo:8.0.10
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - xpay-net

  postgres:
    image: postgres:16.9-bookworm
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: xpay
      POSTGRES_USER: xpayuser
      POSTGRES_PASSWORD: xpaypass
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - xpay-net

volumes:
  mongo_data:
  pg_data:

networks:
  xpay-net:
    driver: bridge
