services:
  postgres:
    image: postgres:16.9-bookworm
    container_name: postgres-db
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: saurabhjojare
      POSTGRES_PASSWORD: Saurabh@123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  kafka:
    image: bitnami/kafka:4.0.0-debian-12-r8
    container_name: kafka-kraft
    ports:
      - "9092:9092"
    environment:
      - KAFKA_KRAFT_MODE=true
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data
    volumes:
      - kafka_data:/bitnami/kafka
    networks:
      - backend
    depends_on:
      - postgres

volumes:
  postgres_data:
  kafka_data:

networks:
  backend:
