server:
  port: 8082
spring:
  application:
    name: payments-service

  datasource:
    url: jdbc:postgresql://localhost:5432/xpay
    username: xpayuser
    password: xpaypass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect