services:

  postgres:
    image: postgres:16.9-bookworm
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: xpay
      POSTGRES_USER: saurabhjojare
      POSTGRES_PASSWORD: Saurabh@123
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - xpay-net

volumes:
  pg_data:

networks:
  xpay-net:
    driver: bridge
