services:
  postgres-wallet:
    image: postgres:18.0-bookworm
    container_name: postgres-xpay-wallet
    environment:
      POSTGRES_USER: saurabhjojare
      POSTGRES_PASSWORD: Saurabh@123
      POSTGRES_DB: xpay-db-wallet
    ports:
      - "5432:5432"
    volumes:
      - postgres_wallet_xpay:/var/lib/postgresql/data
    networks:
      - backend-xpay

  postgres-auth:
    image: postgres:18.0-bookworm
    container_name: postgres-xpay-auth
    environment:
      POSTGRES_USER: saurabhjojare
      POSTGRES_PASSWORD: Saurabh@123
      POSTGRES_DB: xpay-db-auth
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_xpay:/var/lib/postgresql/data
    networks:
      - backend-xpay

  postgres-transactions:
    image: postgres:18.0-bookworm
    container_name: postgres-xpay-transactions
    environment:
      POSTGRES_USER: saurabhjojare
      POSTGRES_PASSWORD: Saurabh@123
      POSTGRES_DB: xpay-db-transactions
    ports:
      - "5434:5432"
    volumes:
      - postgres_transactions_xpay:/var/lib/postgresql/data
    networks:
      - backend-xpay
    depends_on:
      - postgres-wallet
      - postgres-auth

  kafka:
    image: confluentinc/cp-kafka:8.0.1
    container_name: kafka-kraft-xpay
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft mode (no Zookeeper)
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      CLUSTER_ID: 123e4567-e89b-12d3-a456-426614174000
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
    volumes:
      - kafka_data_xpay:/var/lib/kafka/data
    networks:
      - backend-xpay
    depends_on:
      - postgres-wallet
      - postgres-auth

  mongo:
    image: mongo:8.0.10
    container_name: mongo-xpay-user
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: saurabhjojare
      MONGO_INITDB_ROOT_PASSWORD: Saurabh@123
      MONGO_INITDB_DATABASE: xpay-db-user
    volumes:
      - mongo_user_xpay:/data/db
    networks:
      - backend-xpay

  prometheus:
    image: prom/prometheus:v3.6.0
    container_name: prometheus-xpay
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-storage:/prometheus
    networks:
      - backend-xpay

  grafana:
    image: grafana/grafana:12.2.0
    container_name: grafana-xpay
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - backend-xpay
    depends_on:
      - prometheus

volumes:
  postgres_wallet_xpay:
  postgres_auth_xpay:
  mongo_user_xpay:
  kafka_data_xpay:
  postgres_transactions_xpay:
  grafana-storage:
  prometheus-storage:

networks:
  backend-xpay:
    driver: bridge