services:
  mongo:
    image: mongo:8.0.10
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: saurabhjojare
      MONGO_INITDB_ROOT_PASSWORD: Saurabh@123
      MONGO_INITDB_DATABASE: xpay_admin
    networks:
      - xpay-net

volumes:
  mongo_data:

networks:
  xpay-net:
    driver: bridge
