server:
  port: 8080  # Gateway runs on 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          # Define all routes here
          routes:
            - id: auth-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/auth/**
              filters:
                - name: RequestLoggingFilter

            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/users/**
              filters:
                - name: JwtAuthenticationFilter
                - name: RequestLoggingFilter

            - id: admin-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/admin/**
              filters:
                - name: JwtAuthenticationFilter
                - name: RequestLoggingFilter

            - id: wallet-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/wallets/**
              filters:
                - name: JwtAuthenticationFilter
                - name: RequestLoggingFilter


jwt:
  secret: a267206a66f9e659f8ebeaa75090e71b04a626165f1e874130b26a7309fe934e
