server:
  port: 8080  # Gateway runs on 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/users/**
          filters:
            - JwtAuthenticationFilter
            - RequestLoggingFilter
        - id: admin-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/admin/**
          filters:
            - JwtAuthenticationFilter
            - RequestLoggingFilter
